# Generated by Django 4.0.1 on 2022-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_post_options_post_slug_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_banner',
            field=models.ImageField(blank=True, upload_to='blogs/images/'),
        ),
    ]
