# Generated by Django 4.0.1 on 2022-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readmore_body',
            field=models.TextField(default='', max_length=200),
        ),
    ]
