# Generated by Django 4.0.1 on 2022-03-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
