# Generated by Django 4.0.1 on 2022-03-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0003_contact_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phn_num',
        ),
    ]
